//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUNetwork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTIVATION
    {
        public long ID { get; set; }
        public string USER_ID { get; set; }
        public int CODE { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public string STATUS_CODE { get; set; }
    }
}
