//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUNetwork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAVORITE
    {
        public long ID { get; set; }
        public string USER_ID { get; set; }
        public string STATUS_CODE { get; set; }
        public string FAVORITE_TYPE { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
    }
}
