//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUNetwork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GROUP_ACTIVITY
    {
        public int ID { get; set; }
        public long GROUP_ID { get; set; }
        public string USER_ID { get; set; }
        public string DESCRIPTION { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
    }
}
