//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUNetwork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MESSAGES
    {
        public long ID { get; set; }
        public string MESSAGE { get; set; }
        public System.DateTime SEND_DATE { get; set; }
        public string SENDER_USER_ID { get; set; }
        public string RECEIVER_USER_ID { get; set; }
        public System.DateTime RECEIVE_DATE { get; set; }
        public string READ_FLAG { get; set; }
        public System.DateTime READ_DATE { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
    }
}
